#ifndef _SYSTICK_CFG_H_
#define _SYSTICK_CFG_H_


/*
 * OPTIONS :
 *           SYSTICK_TICK_INT_OFF
 *           SYSTICK_TICK_INT_ON
 */
#define SYSTICK_TICK_INT  SYSTICK_TICK_INT_ON

/*
 * OPTIONS :
 *           SYSTICK_CLK_SOURCE_AHB_DIV_BY_8
 *           SYSTICK_CLK_SOURCE_AHB
 */
#define SYSTICK_CLK_SOURCE  SYSTICK_CLK_SOURCE_AHB


#endif
